### ISSUE TITLE
elastix registration results are non-deterministic

### ISSUE THREAD

**Issue by shtankevych** [SuperElastix/elastix#90] opened 2018-12-07 11:39 UTC
Hi, 
We tried elastix 4.8 and 4.9 for registration of CT images with the parameters attached in a txt file. We experience non-deterministic result (final transform parameters - translation and rotation) on different PCs, we noticed it mainly depends on the number of threads used. Results are also non-deterministic on same machine if we use -threads parameter (setting different number of threads to use). Can you advise what could be the root cause of it?
[elastix_params.txt](https://github.com/SuperElastix/elastix/files/2657034/elastix_params.txt)

**Comment by YuchuanQiao** [comment] 2018-12-10 21:59
Because you use a random sampler (ImageSampler "RandomCoordinate") even if you use gradient descent optimizer (Optimizer "StandardGradientDescent").
When you chose full sampler, the result will be deterministic, but it will be very slow.

**Comment by shtankevych** [comment] 2018-12-12 16:56
I found that the problem is not in using (ImageSampler "RandomCoordinate") , since all the random coordinates generation is done in the main thread with fixed seed and thus deterministic, unless someone launches second registration in parallel. The problem occurred in the paralelization of AdvancedNormalizedCorrelation metric. In multi threaded mode generated random coordinates are divided into chunks to be processed by all threads. Each thread does summation of its intermediate results. Since number of threads (and work chunks) may vary, summation is done in different order and is not deterministic depending on the number of threads used. Adding one more elastix parameter (UseMultiThreadingForMetrics "false") fixes the non-determinism by making the metric to be computed in a single thread.

**Comment by YuchuanQiao** [comment] 2018-12-14 23:15
ah ha, I noticed this difference previously, however, this is not an issue for our evaluation. If you want to evaluate the cost function value, you should use (ShowExactMetricValue "true") option. For the whole procedure of elastix registration, different number of threads will result in a slightly different cost function value. The source of the difference is quite difficult to find, e.g. the initialization step, the optimizer initialization step, the gradient calculation step..... elastix is multi-threaded in each component. If you want to dig more, you can check each component step-by-step. otherwise, just ignore this. good luck.

**Comment by shtankevych** [comment] 2018-12-27 14:09
For my usage non-determinism even between machines is a big problem, since results may not be reproducible between different users on their hardware. So far I paused my tries to find the root cause of non-determinism since I found a workaround for my registration scenario - with using nearest neighbor image interpolation I can't reproduce non-determinism between different machines anymore (with bspline and linear I do) and the results seem to be still acceptable.

**Comment by mstaring** [comment] 2018-12-27 18:54
FYI I played with https://itk.org/Doxygen/html/classitk_1_1CompensatedSummation.html at the time. Perhaps it can help you.

I would think that any sufficiently complex algorithm, especially iterative ones, will give slightly different results on different machine with different machine precision. Just out of curiosity, what is your specific use case that requires such a high level of reproducibility?

**Comment by mstaring** [comment] 2018-12-27 18:56
Do you use deep learning methods in your solution as well? Because I would think that those results would also vary slightly between different hardware (GPUs).

**Comment by shtankevych** [comment] 2018-12-28 12:33
> Just out of curiosity, what is your specific use case that requires such a high level of reproducibility?
In my case registration is the first step of the automatic segmentation within a clinical application. Difference in resulting transformation which gets accumulated over 2500 iterations may lead to significantly different final segmentation. Of course there is also a valid question of stability and sensitivity of the further steps.

**Comment by shtankevych** [comment] 2018-12-28 12:38
> Do you use deep learning methods in your solution as well? Because I would think that those results would also vary slightly between different hardware (GPUs).

Nope, I don't use neither. I observe differences in single thread using same debug binaries between Core i7 Win10 x64 machine and Core2Quad Win7 x64 machine.

**Comment by mstaring** [comment] 2019-01-02 08:09
I'm afraid I don't have an out of the box solution for you. 
Perhaps there is literature on this online, since as I said I would think that any sufficiently complex algorithm would have this issue.

I am going to close this issue, but feel free to reopen when necessary.

**Closed by mstaring** 2019-01-02 08:09 UTC
