### ISSUE TITLE
Cmake solution and openCL release 4.9.0

### ISSUE THREAD

**Issue by mfroeling** [SuperElastix/elastix#59] opened 2018-03-30 08:45 UTC
When i build the elastix 4.9 release with OPENCL = True Cmake generates a wrong elxOenCL.vcxproj file that results in a load fail of the elxOpenCL solution

_..\Common\OpenCL\elxOpenCL.vcxproj : error  : File ..\Common\OpenCL\CMakeLists.txt is included into CustomBuild and None item groups. This is not allowed for project items, which can belong to only one item group._ 

It has to do with this line being added in elxOenCL.vcxproj, after removing it the solution loads and compiles without errors.
` <None Include="..\Common\OpenCL\CMakeLists.txt" />`

**Comment by mstaring** [comment] 2018-04-11 14:55
Dear Martijn,
Thank you for reporting this. What compiler did you use?
I just tried with my own setup: win10, vs 14 2015, cmake 3.7.1 and it worked like a charm.
Best, Marius

**Comment by mfroeling** [comment] 2018-04-11 18:34
Dear Marius,

I think the issue could have been my cmake version which was 3.11.0, i did not realize that could also be the cause.

I had tested it for win 10, vs 12 2013, 14 2015 and 15 2017 (with ITK  4.13) all with the same load error.
Other than that one single error all was fine.

Thanks for the response, 
Best Martijn

**Comment by mstaring** [comment] 2018-04-12 09:39
Dear Martijn,

So, the error disappeared when  going to cmake 3.7 ?
Because then we need to take a look for a newer cmake version, which I would also like to support.

Best, Marius

**Comment by AndreaNES** [comment] 2018-05-31 12:28
Dear All,

I would like to report a positive result with the most current version of CMake (and any other tool)

My configuration is as follows:

Windows 10 Pro 64bit 
VS 2017 Community Edition with applicable updates (Version 15.7.2)
CMake 3.11.2
ITK 4.13.0 compiled with default setting, 64bit
CUDA 9.2
GPU = GTX Titan V

Elastix was configured with ELASTIX_USE_OPENCL and all compiled OK without any error.

Cheers,

Andrea

**Comment by mstaring** [comment] 2018-07-16 10:04
I was indeed able to reproduce the problem with CMake 3.11.0. When I upgraded to CMake 3.11.4 the problem went away, so I guess they fixed the issue at their side. 

Thanks for reporting the issue @mfroeling, and also thank you @AndreaNES for reporting the positive result! I am closing this issue.

**Closed by mstaring** 2018-07-16 10:04 UTC
