### ISSUE TITLE
-Winconsistent-missing-override on MacOS

### ISSUE THREAD

**Issue by haampie** [SuperElastix/elastix#110] opened 2019-02-07 15:47 UTC
When compiling on MacOS, there is a very large wall of warnings of the form:

```
elastix-4.9.0/Core/ComponentBaseClasses/elxTransformBase.hxx:79:16: warning: 'Execute' overrides a member function but is not marked
      'override' [-Winconsistent-missing-override]
  virtual void Execute( const Object * caller, const EventObject & )
               ^
/usr/local/include/ITK-4.13/itkCommand.h:62:16: note: overridden virtual function is here
  virtual void Execute(const Object *caller, const EventObject & event) = 0;
```

Can I fix this somehow?

**Comment by pieper** [comment] 2019-02-09 20:04
Yes, this issue is preventing the SlicerElastix extension from working:

https://discourse.slicer.org/t/elastix-extension-for-mac-osx-not-available/5692/2

It should just be a matter of adding the override keyword (in a lot of places).

**Comment by kaspermarstal** [comment] 2019-02-11 21:17
This has been a long-standing issue. We are not working on this atm but we are happy to accept a PR.

**Comment by pieper** [comment] 2019-02-11 23:29
Thanks - I will try suppressing this for now and see if that fixes the slicer extension build.  With the flag everything compiles with no warnings on my local build.

**Comment by mstaring** [comment] 2019-02-12 08:30
@N-Dekker Would you have time to have a look?
It would fit the refactoring for ITK5

**Comment by N-Dekker** [comment] 2019-02-12 10:36
I think `override` is a Good Thing, but it's specific to C++11. So I would like to give priority (1) to getting elastix to produce equivalent or better results with ITKv5 as with ITKv4. Then (2) drop ITKv4 compatibility. Then (3) start using C++11 everywhere in elastix.

**Comment by mstaring** [comment] 2019-02-12 15:25
sounds good!

**Comment by kaspermarstal** [comment] 2019-02-12 20:46
Indeed, can't argue with that 😆

**Comment by mstaring** [comment] 2019-04-02 07:45
@N-Dekker any progress on this?

**Comment by N-Dekker** [comment] 2019-04-02 09:37
@mstaring OK, I'l have a look. Need to figure our how to automate adding those `override` specifiers.  Clang Tidy-Fix should be of help: https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html But somehow my Visual Studio 2017 Clang Power Tools just says

> Start Clang Tidy-Fix
> PROJECT: elastix\Core\elxCore.vcxproj
> Done Clang Tidy-Fix

(While fixing nothing!) Any suggestion is welcome.

**Comment by mstaring** [comment] 2019-04-10 12:47
@N-Dekker does this commit fix this issue?

**Comment by N-Dekker** [comment] 2019-04-10 13:39
@mstaring I think this commit has fixed 95% of the issue: https://github.com/SuperElastix/elastix/commit/285083d01dd923e046a41528db3eadb3e4d435eb  Still busy trying to figure out what to do with macro calls like `itkSetClampMacro`, `itkGetConstReferenceMacro`, etc., that internally might override virtual functions.

However, it's hard to see now when the issue is fixed, as we don't get these warnings on our dashboard, do we?

**Comment by N-Dekker** [comment] 2019-04-28 13:56
I don't see those missing override warnings anymore at our macOS CI builds: https://dev.azure.com/kaspermarstal/Elastix/_build/results?buildId=403

So I think the issue is finally fixed now. Harmen @haampie please check!

**Closed by N-Dekker** 2019-04-28 13:56 UTC

**Comment by haampie** [comment] 2019-04-28 14:06
Yup! Building here and I don't see any warnings (yet, 50% atm)
